<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AfishaVoenmeh.AuthService.Application\AfishaVoenmeh.AuthService.Application.csproj" />
    <ProjectReference Include="..\AfishaVoenmeh.AuthService.Contracts\AfishaVoenmeh.AuthService.Contracts.csproj" />
    <ProjectReference Include="..\AfishaVoenmeh.AuthService.Infrastructure\AfishaVoenmeh.AuthService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
